#Numpy Array


Time(Numpy VS List)

List


In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
my_list=[i for i in range(1000)]
start_time=process_time()
my_list=[i+5 for i in range (1000)]
end_time=process_time()
print("Time taken for process :",-(start_time-end_time))


Time taken for process : 0.0001919709999995689


numpy array


In [ ]:
np_array=np.array([i for i in range(1000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print("Time taken for process :",-(start_time-end_time))

Time taken for process : 0.00013237100000118573


#Numpy Array Analysis


In [ ]:
num_arr=np.array([1,2,3,4,5])
print(num_arr)
type(num_arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
num_arr.shape

(5,)

In [ ]:
arr2=np.array([(1,2,3),(1,5,6),(4,85,5)])


In [ ]:
print(arr2)

[[ 1  2  3]
 [ 1  5  6]
 [ 4 85  5]]


In [ ]:
a=np.eye(4)

In [ ]:
print(a)
print(a+10)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[11. 10. 10. 10.]
 [10. 11. 10. 10.]
 [10. 10. 11. 10.]
 [10. 10. 10. 11.]]


In [ ]:
b=np.random.rand(3,3)

In [ ]:
print(b)

[[0.60773888 0.77079279 0.72507705]
 [0.21017928 0.46269454 0.06587289]
 [0.23161018 0.82500166 0.24329842]]


In [ ]:
c=np.random.randint(10,100,(4,5))

In [ ]:
print(c )

[[67 98 16 21 94]
 [27 10 27 29 92]
 [74 71 71 24 41]
 [78 45 39 99 64]]


#Numpy Array Analysis


In [ ]:
x=np.random.randint(10,100,(4,5))

In [ ]:
print(x)

[[48 41 38 72 58]
 [74 21 20 83 84]
 [65 45 65 84 53]
 [37 10 19 87 96]]


In [ ]:
x.shape

(4, 5)

In [ ]:
x  .size

20

In [ ]:
y=np.random.randint(10,100,(4,5))


In [ ]:
print(x+y)

[[111 111  50 163  91]
 [ 86 115 110 100 173]
 [149  99  92 179 137]
 [ 89  20  64  97 173]]
